#############################################################################################
###Authentication###
//Register new account
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "fullname": "Nguyễn Nhật Lam",
  "email":"nhatlam1695@gmail.com",
  "phonenumber":"0389935371",
  "password": "admin",
  "role": "Admin"
}

###
//GET
GET http://localhost:8080/api/auth/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTcyNzAxYjZjZTBiZDE5NzM2OWY5OWIiLCJ1c2VybmFtZSI6Im5oYXRsYW0xNjk1QGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTYzNDg4OTc1Nn0.m1y4hcFnp5Kc6tfzSW5r6fgujAEhmtR8imw6CFSjOWA

###
//Login account to get token
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "nhatlam1695@gmail.com",
  "password": "admin"
}

###
//Forgot password
POST http://localhost:8080/api/forgotPass/

{
  "email": "hoanglong2012@gmail.com"
}

#############################################################################################
###Category###
//Get categorylist
GET http://localhost:8080/api/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTcyNzAxYjZjZTBiZDE5NzM2OWY5OWIiLCJ1c2VybmFtZSI6Im5oYXRsYW0xNjk1QGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTYzNDg4OTc1Nn0.m1y4hcFnp5Kc6tfzSW5r6fgujAEhmtR8imw6CFSjOWA

###
//Add new category
POST http://localhost:8080/api/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTcyNzAxYjZjZTBiZDE5NzM2OWY5OWIiLCJ1c2VybmFtZSI6Im5oYXRsYW0xNjk1QGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTYzNDg4OTc1Nn0.m1y4hcFnp5Kc6tfzSW5r6fgujAEhmtR8imw6CFSjOWA

{
  "categoryName": "Desserts",
  "categoryData": []
}

###
//Delete category
DELETE http://localhost:8080/api/categories/61660fcc539b3b5539800301
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTcxNWQyOGJlNzM1NzUzMmQzYTQ1MzUiLCJ1c2VybmFtZSI6ImhvYW5nbG9uZzIwMTJAZ21haWwuY29tIiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjM0ODgyNDIzfQ.5IHomKzpHxjGcnVfEPlc4OtL4Y0TeaoRXveYXTkShEk

#############################################################################################
###Food###
//Get all Foods or using ?category={categoryId}
GET http://localhost:8080/api/foods/getFoodsList
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTcyNzAxYjZjZTBiZDE5NzM2OWY5OWIiLCJ1c2VybmFtZSI6Im5oYXRsYW0xNjk1QGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTYzNDg4OTc1Nn0.m1y4hcFnp5Kc6tfzSW5r6fgujAEhmtR8imw6CFSjOWA

###
//Add food into category
POST http://localhost:8080/api/foods/addFoodIntoCategory/61725564bc1bbd8e7444cbe7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTcyNzAxYjZjZTBiZDE5NzM2OWY5OWIiLCJ1c2VybmFtZSI6Im5oYXRsYW0xNjk1QGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTYzNDg4OTc1Nn0.m1y4hcFnp5Kc6tfzSW5r6fgujAEhmtR8imw6CFSjOWA

{
  "url": "https://firebasestorage.googleapis.com/v0/b/android-e3098.appspot.com/o/Mung-Bean.jpeg?alt=media&token=9a773f1e-a6af-42e5-a7de-86424a897bb0",
  "weight": "200gr",
  "price": 35000,
  "name": "Mung Bean Tong Shui",
  "nation": "China",
  "status": "NORMAL",
  "description": "Less Sweet, No Santan"
}

###
//Delete Foods in category
DELETE http://localhost:8080/api/foods/617255acbc1bbd8e7444cbf2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTcyNzAxYjZjZTBiZDE5NzM2OWY5OWIiLCJ1c2VybmFtZSI6Im5oYXRsYW0xNjk1QGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTYzNDg4OTc1Nn0.m1y4hcFnp5Kc6tfzSW5r6fgujAEhmtR8imw6CFSjOWA

#############################################################################################
###Favorites###
GET http://localhost:8080/api/favorites/getFavorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTcyNzAxYjZjZTBiZDE5NzM2OWY5OWIiLCJ1c2VybmFtZSI6Im5oYXRsYW0xNjk1QGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTYzNTA1NDk5MX0.Fx0sGoD-etRarYQufIpaSjaeH4Rl1v1qZ01pcTWCOWM

###
POST http://localhost:8080/api/foods/addFoodIntoFavorite/616661ab6212f38ff7dcb483
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTcyNzAxYjZjZTBiZDE5NzM2OWY5OWIiLCJ1c2VybmFtZSI6Im5oYXRsYW0xNjk1QGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTYzNTA1NDk5MX0.Fx0sGoD-etRarYQufIpaSjaeH4Rl1v1qZ01pcTWCOWM

###
DELETE http://localhost:8080/api/foods/deleteFoodFromFavorite/616661ab6212f38ff7dcb483
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTcyNzAxYjZjZTBiZDE5NzM2OWY5OWIiLCJ1c2VybmFtZSI6Im5oYXRsYW0xNjk1QGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTYzNDg4OTc1Nn0.m1y4hcFnp5Kc6tfzSW5r6fgujAEhmtR8imw6CFSjOWA

#############################################################################################
###Orders###
GET http://localhost:8080/api/orders/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTcyNzAxYjZjZTBiZDE5NzM2OWY5OWIiLCJ1c2VybmFtZSI6Im5oYXRsYW0xNjk1QGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTYzNDg4OTc1Nn0.m1y4hcFnp5Kc6tfzSW5r6fgujAEhmtR8imw6CFSjOWA

###
POST http://localhost:8080/api/orders/createOrders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTcyNzAxYjZjZTBiZDE5NzM2OWY5OWIiLCJ1c2VybmFtZSI6Im5oYXRsYW0xNjk1QGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTYzNDg4OTc1Nn0.m1y4hcFnp5Kc6tfzSW5r6fgujAEhmtR8imw6CFSjOWA

{
  "total": 115000,
  "points": 115,
  "orderDetail": [
    {
      "url": "https://firebasestorage.googleapis.com/v0/b/android-e3098.appspot.com/o/Soy-Custard.jpeg?alt=media&token=42bd17b3-286f-4e48-b158-73049ecdeff3",
      "weight": "500gr",
      "price": 35000,
      "name": "Tau Fu Fah",
      "nation": "Austria",
      "status": "NEW",
      "quantity": 1,
      "description": "Brown Sugar Separated"
    },
    {
      "url": "https://firebasestorage.googleapis.com/v0/b/android-e3098.appspot.com/o/Mineral-Water.jpeg?alt=media&token=9b706cf6-b680-4392-bd4a-aa60f9dee50c",
      "weight": "500ml",
      "price": 30000,
      "name": "Mineral Water 500ml",
      "nation": "Vietnam",
      "status": "NEW",
      "quantity": 1,
      "description": ""
    },
    {
      "url": "https://firebasestorage.googleapis.com/v0/b/android-e3098.appspot.com/o/Steam-White-Tofu-Set.jpeg?alt=media&token=9ed181e5-2206-421f-af8b-026102ad079d",
      "weight": "500gr",
      "price": 90000,
      "name": "Steamed Soft Tofu Set",
      "nation": "Vietnam",
      "status": "NEW",
      "quantity": 1,
      "description": "Soft Tofu Steamed and Topped with Soy Chunks. Set Comes With Rice of Your Choice, 1 Stir Fried Vege, 1 Salad (Vegetarian)."
    }
  ]
}