#############################################################################################
###Authentication###
//Register new account
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "fullname": "Nguyễn Hoàng Long",
  "email":"hoanglong2012@gmail.com",
  "phonenumber":"0123456789",
  "password": "admin1"
}

###
//GET
GET http://localhost:8080/api/auth/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTY4ODY1MjhjOThmMmU2ZDMxZGMwOTkiLCJ1c2VybmFtZSI6IjIwMTJAZ21haWwuY29tIiwiZnVsbG5hbWUiOiJOZ3V54buFbiBIb8OgbmcgTG9uZyIsInBob25lIjoiMDEyMzQ1Njc4OSIsImlhdCI6MTYzNDI0MDA4Mn0.H5wXou40wX_RNIR8uwxc_GCH9vSCRYArZXboBQMv_B4

###
//Login account to get token
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "hoanglong2012@gmail.com",
  "password": "admin1"
}

#############################################################################################
###Category###
//Get categorylist
GET http://localhost:8080/api/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTY2MGFlNzdlMzUzOWQyZmZjYjQ2NzkiLCJ1c2VybmFtZSI6Im5oYXRsYW0xNjk1QGdtYWlsLmNvbSIsImZ1bGxuYW1lIjoiTmd1eeG7hW4gTmjhuq10IExhbSIsInBob25lIjoiMDM4OTkzNTM3MSIsImlhdCI6MTYzNDA3Nzk1OH0.WUYr0XPdFptbIFxpzrXEHW7emkEZZbVe7I4iaT7PTl0

###
//Add new category
POST http://localhost:8080/api/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTY2MGFlNzdlMzUzOWQyZmZjYjQ2NzkiLCJ1c2VybmFtZSI6Im5oYXRsYW0xNjk1QGdtYWlsLmNvbSIsImZ1bGxuYW1lIjoiTmd1eeG7hW4gTmjhuq10IExhbSIsInBob25lIjoiMDM4OTkzNTM3MSIsImlhdCI6MTYzNDA3Nzk1OH0.WUYr0XPdFptbIFxpzrXEHW7emkEZZbVe7I4iaT7PTl0

{
  "categoryName": "Sets",
  "categoryData": []
}

###
//Delete category
DELETE http://localhost:8080/api/categories/6166278bfee5ecd9ac85ea90
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTY2MGFlNzdlMzUzOWQyZmZjYjQ2NzkiLCJ1c2VybmFtZSI6Im5oYXRsYW0xNjk1QGdtYWlsLmNvbSIsImZ1bGxuYW1lIjoiTmd1eeG7hW4gTmjhuq10IExhbSIsInBob25lIjoiMDM4OTkzNTM3MSIsImlhdCI6MTYzNDA3Nzk1OH0.WUYr0XPdFptbIFxpzrXEHW7emkEZZbVe7I4iaT7PTl0

#############################################################################################
###Food###
//Get all Foods or using ?category={categoryId}
GET http://localhost:8080/api/foods/getFoodsList
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTY2MGFlNzdlMzUzOWQyZmZjYjQ2NzkiLCJ1c2VybmFtZSI6Im5oYXRsYW0xNjk1QGdtYWlsLmNvbSIsImZ1bGxuYW1lIjoiTmd1eeG7hW4gTmjhuq10IExhbSIsInBob25lIjoiMDM4OTkzNTM3MSIsImlhdCI6MTYzNDA3Nzk1OH0.WUYr0XPdFptbIFxpzrXEHW7emkEZZbVe7I4iaT7PTl0

###
//Add food into category
POST http://localhost:8080/api/foods/addFoodIntoCategory/61660fcc539b3b5539800301
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTY2MGFlNzdlMzUzOWQyZmZjYjQ2NzkiLCJ1c2VybmFtZSI6Im5oYXRsYW0xNjk1QGdtYWlsLmNvbSIsImZ1bGxuYW1lIjoiTmd1eeG7hW4gTmjhuq10IExhbSIsInBob25lIjoiMDM4OTkzNTM3MSIsImlhdCI6MTYzNDA3Nzk1OH0.WUYr0XPdFptbIFxpzrXEHW7emkEZZbVe7I4iaT7PTl0

{
  "url": "https://firebasestorage.googleapis.com/v0/b/android-e3098.appspot.com/o/Soy-Custard.jpeg?alt=media&token=42bd17b3-286f-4e48-b158-73049ecdeff3",
  "weight": "500gr",
  "price": 35000,
  "name": "Tau Fu Fah",
  "nation": "Austria",
  "status": "NEW",
  "description": "Brown Sugar Separated"
}

###
//Delete Foods in category
DELETE http://localhost:8080/api/foods/61661e834144cd9286ae7cae
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTY2MGFlNzdlMzUzOWQyZmZjYjQ2NzkiLCJ1c2VybmFtZSI6Im5oYXRsYW0xNjk1QGdtYWlsLmNvbSIsImZ1bGxuYW1lIjoiTmd1eeG7hW4gTmjhuq10IExhbSIsInBob25lIjoiMDM4OTkzNTM3MSIsImlhdCI6MTYzNDA3Nzk1OH0.WUYr0XPdFptbIFxpzrXEHW7emkEZZbVe7I4iaT7PTl0

###
#Favorite
POST http://localhost:8080/api/foods/addFoodIntoFavorite/61665ea5384e9ac222992c04
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTZiNjQ2ZjJlNjM4MDA0ZDRmNDlhZmIiLCJ1c2VybmFtZSI6ImhvYW5nbG9uZzIwMTJAZ21haWwuY29tIiwiZnVsbG5hbWUiOiJOZ3V54buFbiBIb8OgbmcgTG9uZyIsInBob25lIjoiMDEyMzQ1Njc4OSIsImlhdCI6MTYzNDQ0MjAzMH0.3jLJrArPgxxyrsORI4x1uTZrYk1Y_gFCcaXlIXLOG1U
